### ISSUE TITLE
Difference between how UI and Cockpit Composer UI call Amazon images

### ISSUE THREAD

**Issue by atodorov** [RedHatInsights/image-builder-frontend#15] opened 2020-10-12 11:27 UTC
https://github.com/osbuild/image-builder-frontend/commit/404a80e59c0951c8de3fb595c385cbf529d52ff9 uses 
"Amazon Machine Image (.raw)" which is shown in the UI while the Cockpit Composer counterpart uses
"Amazon Machine Image Disk (.ami)":

![cockpit_composer](https://user-images.githubusercontent.com/1002300/95741547-1bbe8d80-0c97-11eb-8a31-6b75b0903b00.png)

**Comment by jkozol** [comment] 2021-06-02 09:53
Closing this since the way cockpit-composer and image-builder-frontend display image types is substantially different now, by design.

**Closed by jkozol** 2021-06-02 09:53 UTC
