### ISSUE TITLE
Overall image status shows fail if there is at least one failed clone

### ISSUE THREAD

**Issue by jrusz** [RedHatInsights/image-builder-frontend#950] opened 2023-02-06 11:29 UTC
As you can see in the screenshot no matter what is happening if there is at least one failure it shows that on the top image, is that expected? 
![image](https://user-images.githubusercontent.com/55534579/216960287-fc629c97-21f8-4e97-89d1-88e0c85c5e43.png)

**Comment by lucasgarfield** [comment] 2023-02-06 11:52
Yes, this behavior (display the highest priority, or worst case, on the main status row) was defined by the design team. It might be worth revisiting.

**Comment by lucasgarfield** [comment] 2023-02-10 10:10
Going to close this issue for now since it is not a bug.

**Closed by lucasgarfield** 2023-02-10 10:10 UTC
