### ISSUE TITLE
Wizard: Target environment buttons bug

### ISSUE THREAD

**Issue by lucasgarfield** [RedHatInsights/image-builder-frontend#777] opened 2022-08-17 16:14 UTC
The AWS, GCP, and Azure buttons lose their outlines when selected. That is not the correct behavior, they should retain their outlines. Interestingly, this only occurs when they are selected using the mouse - select them with the keyboard (using the spacebar) and the outline remains.
![image](https://user-images.githubusercontent.com/95542540/185189484-3b029711-568f-4cc0-9c49-f05534ef2bb1.png)
![image](https://user-images.githubusercontent.com/95542540/185189506-7ca13abf-4dda-4e4a-831f-dc659f882f69.png)

**Comment by AditSaxena** [comment] 2022-09-10 14:05
@lucasgarfield 
Hi
I would like to work on this issue.
Can you assign it to me ?

**Comment by arburka** [comment] 2022-09-14 02:29
Is this browser specific?

**Comment by lucasgarfield** [comment] 2022-09-14 07:09
The issue is present in both Firefox and Chromium. I have not tested other browsers.

**Comment by arburka** [comment] 2022-09-14 17:24
I don't know if this is specifically happening on stage or a version I do not have access to, but I couldn't reproduce it on Chrome.

**Closed** 2022-10-25 16:12 UTC
Labels: good first issue, SPUR
