### ISSUE TITLE
ddf packages:  when user focus is in search bar, 'enter' should search, not go to next step

### ISSUE THREAD

**Issue by Gundersanne** [RedHatInsights/image-builder-frontend#254] opened 2021-07-12 17:01 UTC
![image](https://user-images.githubusercontent.com/11140201/125327506-7a5a8a00-e343-11eb-8f78-5232c60b91e9.png)

**Comment by ochosi** [comment] 2021-08-10 22:12
Seems related to (or duplicate of?) #92

**Closed** 2021-11-02 00:26 UTC
Labels: SPUR
